### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by PaulSolt** [MikeMcQuaid/GitHub-Markdown-Font-Settings.tmbundle#1]
I have no idea how to use this font settings.

1. I've double clicked the .tmbundle to install it.
2. I see it in the TextMate 2 Preferences > Bundles list
3. It's Checked, but now I don't know how to use it. It's not a theme... is this for preview? Right now that's not working because I tried Fletcher's multimarkdown markdown .tmbundle ...
    1. Does this conflict with <https://github.com/fletcher/markdown.tmbundle#installation> ?

Thanks!

**Comment by MikeMcQuaid** [comment]
It affects the syntax highlighting fonts for GitHub Markdown bundle according to these features: https://github.com/MikeMcQuaid/GitHub-Markdown-Font-Settings.tmbundle#features

**Comment by PaulSolt** [comment]
Mike,

When I enable it, I don't see a difference. Maybe I'm a TextMate bundle newbie.

Is this all I need to do to activate it? Or is there another step?

<img width="1234" alt="markdowntextmateissue" src="https://cloud.githubusercontent.com/assets/371902/25511711/82777da6-2b96-11e7-8ea9-ff5de7928134.png">

Thanks!

**Comment by MikeMcQuaid** [comment]
You need to have `Markdown (GitHub)` also enabled.
